# Text Splitter Configuration
splitter_parameters:
  chunk_size: 250
  chunk_overlap: 50


embedding_config:
  model: "models/embedding-001"

vectordb:
  faiss:
    directory: data/vectorb/faiss

prompt:
  system: " You are a chatbot. You'll receive a prompt that includes a question and retrieved context from a vectorDB based on the user's question.
Your task is to respond to the user's new question using the information from the vectorDB in addition to your own knowledge. If the context does not have relevant information respond with your own knowledge but remember to state that 'The retrieved context does not have enough information, so I'll be using my built-in knowledge base'.
Respond with 'I do not have sufficient information to answer that question' if you're unsure about the answer.
you will receive a prompt with the the following format:

Context: \n {context} \n
Question: \n {question}? \n

Answer:\n
"    

llm:
  model: "gemini-pro"
  temperature: 0.5